SUBDIRS= .
INCLUDES = -I${master_top_srcdir}/src/include -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES =			\
        mpid_1s.c				\
        mpid_win_accumulate.c			\
        mpid_win_create.c			\
        mpid_win_fence.c			\
        mpid_win_free.c				\
        mpid_win_get.c				\
        mpid_win_lock.c				\
        mpid_win_pscw.c				\
        mpid_win_put.c				\
        mpidi_win_control.c
