SUBDIRS= . coll comm misc mpix onesided pamix pt2pt
INCLUDES = -I${master_top_srcdir}/src/include -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES =			\
        mpid_buffer.c				\
        mpid_finalize.c				\
        mpid_init.c				\
        mpid_iprobe.c				\
        mpid_probe.c				\
        mpid_progress.c				\
        mpid_recvq.c				\
        mpid_request.c				\
        mpid_time.c				\
        mpid_vc.c				\
        mpidi_env.c
