COMPILE = myupcc -v cg.c mmio.o wtime.c c_print_results.c c_randdp.c c_timers.c -lm -lcxml
HPCOMPILE = upc -O cg.c mmio.o wtime.c c_print_results.c c_randdp.c c_timers.c -lm -lcxml



all: mmio.o berkeley hp mupc
#	myupcc -v -o cg-elan2 cg.c mmio.o wtime.c c_print_results.c c_randdp.c c_timers.c -lm -lcxml -network elan -T 2
	

mmio.o:
	cc -O4 -tune host -inline all -c mmio.c


berkeley: mmio.o
	$(COMPILE) -o cg-elan1 -T 1 -network elan
	$(COMPILE) -o cg-mpi1  -T 1 -network mpi
	$(COMPILE) -o cg-elan2 -T 2 -network elan
	$(COMPILE) -o cg-mpi2  -T 2 -network mpi
	$(COMPILE) -o cg-elan4 -T 4 -network elan
	$(COMPILE) -o cg-mpi4  -T 4 -network mpi
	$(COMPILE) -o cg-elan8 -T 8 -network elan
	$(COMPILE) -o cg-mpi8  -T 8 -network mpi
	$(COMPILE) -o cg-elan16 -T 16 -network elan
	$(COMPILE) -o cg-mpi16  -T 16 -network mpi
	$(COMPILE) -o cg-elan32 -T 32 -network elan
	$(COMPILE) -o cg-mpi32  -T 32 -network mpi

hp: mmio.o
	$(HPCOMPILE) -o cghp-elan1 -fthreads 1
	$(HPCOMPILE) -o cghp-elan2 -fthreads 2
	$(HPCOMPILE) -o cghp-elan4 -fthreads 4
	$(HPCOMPILE) -o cghp-elan8 -fthreads 8
	$(HPCOMPILE) -o cghp-elan16 -fthreads 16
	$(HPCOMPILE) -o cghp-elan32 -fthreads 32

mupc:
	cc -c -O4 -tune host -inline all c_print_results.c c_randdp.c c_timers.c mmio.c wtime.c
	mupcc -c cg.c -fthreads 1
	cc -o cg-mupc1 -pthread *.o -lm /usr/users/1/bonachea/UPC/mupc-install/lib/libmupc.a -lmpi -lcxml
	mupcc -c cg.c -fthreads 2
	cc -o cg-mupc2 -pthread *.o -lm /usr/users/1/bonachea/UPC/mupc-install/lib/libmupc.a -lmpi -lcxml
	mupcc -c cg.c -fthreads 4
	cc -o cg-mupc4 -pthread *.o -lm /usr/users/1/bonachea/UPC/mupc-install/lib/libmupc.a -lmpi -lcxml
	mupcc -c cg.c -fthreads 8
	cc -o cg-mupc8 -pthread *.o -lm /usr/users/1/bonachea/UPC/mupc-install/lib/libmupc.a -lmpi -lcxml
	mupcc -c cg.c -fthreads 16
	cc -o cg-mupc16 -pthread *.o -lm /usr/users/1/bonachea/UPC/mupc-install/lib/libmupc.a -lmpi -lcxml
	mupcc -c cg.c -fthreads 32
	cc -o cg-mupc32 -pthread *.o -lm /usr/users/1/bonachea/UPC/mupc-install/lib/libmupc.a -lmpi -lcxml


clean:
	rm -f cg-elan* cg-mpi* cghp-elan* cg-mupc*
	rm -f *.o  whirl2c.h *.w2c.c *.w2c.h $(UPC_OBJS) *_startup_tmp.* *.global_data.c *_symbols *.B *.N *.t *.i *.upc.c upc{c,r}-sizes

