/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /var/local/cvs/upcr/detect-upc/scanner.c,v 1.1 2006/03/29 15:42:24 bonachea Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
static yyconst short int yy_accept[540] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,   11,    9,   11,   10,   10,
       10,   10,   10,   10,   10,   11,   11,   19,   18,   19,
       15,   14,   12,   15,   25,   24,   25,   33,   30,   33,
       33,   33,   33,   33,   34,   34,   34,   21,   34,   34,
       34,   27,   34,    0,   10,   10,   10,   10,   10,   10,
       10,   10,    0,    0,    0,    0,    0,    0,   17,   16,
       14,   12,    0,   13,   23,   22,   33,   33,   33,   33,
        0,    0,    0,    0,    0,    0,    0,   21,    0,   21,
        0,    0,    0,    0,   21,    0,    0,   27,    0,   27,

        0,    0,    0,    0,   27,    0,    3,   10,   10,   10,
       10,   10,   10,   10,    0,    0,    0,    0,    0,   33,
       33,   33,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   10,   10,   10,   10,   10,   10,   10,
        0,    0,    0,   33,   33,   33,    0,    0,    0,    0,
        0,    0,    0,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    0,    0,    0,   33,   33,   33,    0,    0,
        0,    0,    0,    0,    0,   10,   10,   10,   10,    8,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,    0,    0,
        0,   33,   31,    0,    0,    0,    0,    0,    0,    0,
       10,    7,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    0,    1,    0,    0,   28,    0,    0,    0,    0,
        0,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    7,   10,   10,    7,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    7,    0,    0,    0,    0,   21,
        0,    0,   27,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,    0,    0,    0,    0,    0,    0,
        0,    0,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,    7,    7,   10,   10,   10,
        7,    0,    0,    0,    0,    0,    0,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,    7,
       10,   10,    0,    0,    0,    0,    0,    0,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    0,    0,    0,   21,    0,    0,   27,
        0,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   10,   10,   10,   10,    7,   10,   10,
       10,   10,   10,   10,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   10,   10,   10,    7,   10,   10,
       10,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   10,   10,   10,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   10,   10,   10,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       10,    5,    0,    0,    6,    0,   32,    0,    0,    0,
        0,    0,   10,    0,    0,    0,    0,    0,    0,    0,
       10,    0,    4,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   20,    0,   20,    0,   26,
        0,   26,    0,    0,    0,    2,    0,   29,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    9,
        1,    9,    1,    1,   10,   11,   12,   13,   14,   15,
       15,   16,   17,   15,   18,   19,   20,   15,   21,   22,
       15,   23,   24,   25,   26,   15,   15,   27,   28,   29,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   15,   43,   44,   45,   46,
       47,   48,   15,   49,   50,   51,   52,   15,   53,   54,
       55,   56,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    3,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[558] =
    {   0,
        0,   52,    3,    4,  104,  136,    6,    7,  168,  218,
        0,   10,    0,   14,  854,  855,  855,  849,    0,  824,
      835,  828,  811,    0,  800,   19,   25,  855,  855,   14,
      855,   37,    0,  815,  855,  855,   32,  855,  855,    0,
      808,   19,   41,   72,  855,  842,   62,   83,   45,  841,
       87,   92,   96,  837,    0,  817,  818,  828,  795,  804,
      788,  800,  109,  115,  144,  119,  793,  785,  855,  855,
      121,    0,  801,  855,  855,  855,    0,  788,  797,  781,
      126,  130,  146,  148,  787,  779,  824,  855,  155,  159,
      177,  179,  183,  193,  199,   76,  823,  855,  201,  205,

      209,  211,  226,  230,  232,  116,  855,  809,  810,  790,
      788,  772,  778,  786,  234,  236,  251,  772,  783,  782,
      766,  772,  240,  242,  253,  767,  778,  249,  762,  259,
      261,  761,  262,  786,  798,  787,  752,  767,  768,  276,
        0,  765,  762,  747,  762,  763,    0,  760,  757,  762,
       26,  761,   56,  780,  780,  782,  753,  753,  738,  232,
       37,  744,  228,  743,  739,  747,  737,  742,  744,  740,
      734,  745,  774,  281,  732,  738,  738,  723,  769,  283,
      727,  731,  227,  730,  267,  759,  744,  740,  729,    0,
      728,  725,  719,  713,  714,  722,  713,  709,  719,  709,

      719,  709,  702,  718,  701,  701,  705,  706,  744,  292,
      712,  708,    0,  741,  296,  709,  697,  284,  696,  289,
      727,    0,  706,  689,  695,   29,  687,  699,  689,  697,
      698,  693,  695,   57,  290,  687,  678,  689,  688,  678,
      673,  720,  855,  173,  719,  855,  299,  687,  303,  686,
      305,  708,  679,  671,  109,  680,  673,  671,  663,  674,
      667,    0,  676,  665,  675,  659,  668,  653,  666,  664,
      664,  650,  666,  663,    0,  329,  331,  333,  339,  341,
      343,  345,  347,  679,  655,  654,  651,  647,  655,  642,
      649,  646,  645,  176,  317,  633,  636,  635,  634,  629,

      636,  634,  644,  637,  631,  630,  350,   20,  629,  352,
       39,  628,  654,  636,  622,  628,  635,  621,  627,  612,
      634,  632,  623,  613,  614,    0,    0,  623,  620,  613,
        0,  623,  622,  334,  621,  336,  620,  643,  610,  598,
      605,  608,  594,  611,  149,  604,  591,  595,  607,    0,
      610,  604,  355,  357,  359,  361,  363,  371,  624,  604,
      590,  603,  605,  599,  589,  591,  580,  586,  588,  593,
      592,  591,  578,  373,  376,  382,  386,  392,  398,  403,
      405,  594,  584,  591,  577,  584,  578,  579,  584,  572,
      571,  572,  578,  582,  576,  562,  564,  578,  559,  364,

      563,  368,  562,  583,  550,  561,  565,    0,  556,  551,
      558,  564,  560,  550,  561,  552,   81,  559,  558,  559,
      276,  555,  366,  554,  573,  551,  544,    0,  551,  553,
      534,  537,  549,  533,  539,  547,  532,  529,  156,  544,
      270,  543,  546,  527,  539,  535,  517,  519,  533,  532,
      530,  515,  377,  513,  379,  512,  549,  526,  517,  522,
      521,  525,  506,  509,  517,  521,  384,  505,  387,  504,
      507,  855,  513,  497,  855,  511,  855,  495,  383,  510,
      408,  509,  497,  495,  504,  493,  395,  507,  412,  506,
      502,  501,  855,  500,  374,  488,  393,  487,  500,  499,

      410,  485,  413,  477,  473,  410,  389,  398,  414,  395,
      388,  273,  415,  262,  424,  235,  237,  171,  435,  444,
      446,  448,  150,  142,  450,  452,  458,  460,  462,  464,
      466,  469,  471,  473,  475,  478,  480,  482,  855,  485,
      488,  491,  494,  497,  500,  503,  506,  188,  100,  509,
       11,  512,  515,  518,  521,  524,  527
    } ;

static yyconst short int yy_def[558] =
    {   0,
      540,  540,  541,  541,  542,  542,  543,  543,  544,  544,
      545,  546,  545,  547,  539,  539,  539,  539,  548,  548,
      548,  548,  548,  548,  548,  539,  539,  539,  539,  539,
      539,  539,  549,  550,  539,  539,  539,  539,  539,  551,
      551,  551,  539,  539,  539,  552,  552,  539,  552,  553,
      553,  539,  553,  539,  548,  548,  548,  548,  548,  548,
      548,  548,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  549,  550,  539,  539,  539,  551,  551,  551,  551,
      539,  539,  539,  539,  539,  539,  552,  539,  552,  539,
      552,  539,  539,  552,  539,  552,  553,  539,  553,  539,

      553,  539,  539,  553,  539,  553,  539,  548,  548,  548,
      548,  548,  548,  548,  539,  539,  539,  539,  539,  551,
      551,  551,  539,  539,  539,  539,  539,  539,  539,  552,
      539,  539,  553,  548,  548,  548,  548,  548,  548,  548,
      554,  539,  539,  551,  551,  551,  555,  539,  539,  539,
      552,  539,  553,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  554,  539,  539,  551,  551,  551,  555,  539,
      539,  539,  552,  539,  553,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  556,  539,
      539,  551,  551,  557,  539,  539,  539,  552,  539,  553,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  556,  539,  539,  557,  539,  539,  539,  552,  539,
      553,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  539,  539,  539,  552,  539,
      539,  553,  539,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  539,  539,  539,  552,  539,  539,
      553,  539,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  539,  539,  552,  539,  553,  539,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  539,  539,  552,  539,  553,  539,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  539,  539,  552,  539,  539,  553,  539,
      539,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  539,  539,  539,  539,  539,  539,  552,

      539,  553,  539,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  539,  539,  539,  539,  539,  539,
      552,  539,  553,  539,  548,  548,  548,  548,  548,  548,
      548,  539,  539,  539,  539,  539,  539,  539,  552,  539,
      553,  539,  548,  548,  548,  539,  539,  539,  539,  539,
      539,  539,  552,  539,  553,  539,  548,  548,  548,  539,
      539,  539,  539,  539,  539,  539,  552,  539,  553,  539,
      548,  539,  539,  539,  539,  539,  539,  539,  552,  539,
      553,  539,  548,  539,  539,  539,  552,  539,  553,  539,
      548,  539,  539,  539,  552,  539,  553,  539,  539,  539,

      552,  539,  553,  539,  539,  539,  552,  539,  553,  539,
      539,  539,  552,  539,  553,  539,  539,  539,  552,  539,
      553,  539,  539,  539,  552,  539,  539,  539,  553,  539,
      539,  539,  539,  539,  539,  539,  539,  539,    0,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539
    } ;

static yyconst short int yy_nxt[912] =
    {   0,
       16,   16,   16,   17,   16,   18,   29,   29,   16,   36,
       36,   47,   48,   77,   49,   51,   52,   69,   53,   20,
       63,   63,   88,   64,   21,   22,   65,   65,   88,   16,
       16,   16,   66,   30,   30,   75,   37,   37,   71,   71,
       60,   98,   81,   81,   70,   82,   94,   95,   23,   24,
       61,   25,   16,   26,   26,   17,   27,   18,   98,   79,
       16,  255,   76,   89,   90,  183,   91,  334,   67,   80,
      194,   20,   68,   83,   83,  256,   21,   22,   88,   84,
      195,   16,   16,   16,   92,   92,  336,   93,   99,  100,
      264,  101,   96,  102,  102,  185,  103,  104,  105,  265,

       23,   24,   72,   25,   31,   32,   32,   31,   31,   31,
       63,   63,   31,   64,  434,   85,  115,  115,   98,   86,
      116,  116,   71,   71,  130,  117,  117,   81,   81,  435,
       82,  123,  123,   34,   31,   31,   31,   32,   32,   31,
       31,   31,  287,  106,   31,   65,   65,   83,   83,  124,
      124,   66,  288,   84,  125,  125,   89,   90,   88,   91,
       92,   92,   68,   93,  133,   34,   31,   31,   38,   38,
       38,   39,   38,   38,  276,  276,   38,   86,   94,   95,
       92,   92,  366,   93,  128,  128,  367,   67,  453,   85,
       55,   68,  368,   86,   94,   95,  534,   38,   38,   38,

      128,  128,   99,  100,  533,  101,  102,  102,  322,  103,
      104,  105,  102,  102,  524,  103,   41,   42,   38,   43,
       43,   39,   44,   38,   96,  323,   38,  131,  131,   88,
      129,  104,  105,  131,  131,  115,  115,  116,  116,  141,
       96,  123,  123,  124,  124,  147,  129,   38,   38,   38,
      128,  128,  116,  116,  124,  124,  106,  117,  117,  125,
      125,   88,  131,  131,   98,  197,   41,   42,  191,   98,
      192,  218,   98,  132,  198,  193,  199,  106,   88,  132,
      523,   68,  210,  210,  215,  215,   88,   86,   66,  522,
       84,   98,  151,  210,  210,  153,  129,  215,  215,   66,

      277,  277,  455,   84,  279,  280,  282,  283,  132,  160,
      161,  220,  439,  162,  163,  164,  520,  249,  518,  165,
      166,  167,  251,  168,  169,  266,  170,  171,  172,  267,
      276,  276,  277,  277,  307,  307,   88,  268,   98,  269,
      279,  280,  307,  307,  310,  310,  282,  283,  310,  310,
      324,  307,  307,  310,  310,  325,  374,  374,  375,  375,
      376,  377,  378,  378,  379,  380,   88,  326,   98,  355,
       98,  357,  381,  381,  374,  374,   88,  375,  375,   88,
      305,   98,  306,  376,  377,   88,   88,  378,  378,   98,
      308,   88,  309,  378,  378,   98,  311,   88,  312,  379,

      380,  309,  441,  312,  381,  381,  381,  381,  394,  421,
       98,  398,   88,  423,   98,   98,   98,   88,  487,  400,
      501,  395,  396,  401,  397,  399,   98,  495,  467,  401,
      469,  479,  513,  517,  481,  402,  525,  526,  516,  503,
      403,  514,  403,  489,  497,  527,  528,  529,  530,  531,
      532,  525,  526,  527,  528,  507,  512,  515,  509,  527,
      528,  527,  528,  529,  530,  531,  532,  531,  532,  519,
      531,  532,  535,  536,  537,  538,  535,  536,  521,  535,
      536,  537,  538,  537,  538,   19,   19,   19,   28,   28,
       28,   33,   33,   33,   35,   35,   35,   40,   40,   40,

       45,   45,   45,   46,   46,   46,   50,   50,   50,   73,
       73,   73,   87,   87,   87,   97,   97,   97,  173,  511,
      173,  179,  510,  179,  242,  242,  242,  245,  245,  245,
      508,  506,  505,  504,  502,  500,  499,  326,  498,  496,
      494,  493,  492,  491,  490,  488,  486,  485,  484,  475,
      483,  482,  480,  478,  477,  476,  475,  474,  473,  472,
      471,  326,  428,  470,  468,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  454,  452,  451,  450,
      449,  448,  447,  446,  331,  445,  262,  444,  408,  443,
      442,  440,  438,  437,  436,  433,  432,  431,  428,  262,

      430,  222,  429,  428,  427,  426,  425,  424,  422,  420,
      419,  418,  417,  416,  415,  350,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  393,  326,  392,
      391,  390,  389,  388,  387,  386,  385,  384,  262,  383,
      350,  382,  350,  373,  372,  371,  370,  369,  365,  364,
      363,  362,  361,  360,  359,  358,  356,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  275,
      342,  341,  340,  339,  338,  337,  335,  333,  332,  331,
      330,  329,  328,  275,  327,  327,  327,  327,  321,  222,
      320,  319,  318,  317,  316,  315,  314,  313,  304,  303,

      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  275,  291,  290,  289,  262,  286,  285,  284,  281,
      278,  246,  243,  275,  274,  273,  272,  271,  270,  263,
      262,  261,  260,  259,  258,  257,  254,  253,  252,  222,
      250,  248,  247,  246,  213,  244,  243,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  190,  223,  222,  221,  219,
      217,  216,  214,  213,  213,  212,  211,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  196,  190,  190,
      189,  188,  187,  186,  184,  182,  181,  180,  178,  177,

      176,  175,  174,  159,  158,  157,  156,  155,  154,  152,
      150,  149,  148,  146,  145,  144,  143,  142,  140,  139,
      138,  137,  136,  135,  134,   98,   88,  127,  126,  122,
      121,  120,   74,  119,  118,  114,  113,  112,  111,  110,
      109,  108,  107,   98,   88,   78,   74,   62,   59,   58,
       57,   56,   54,  539,   15,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539
    } ;

static yyconst short int yy_chk[912] =
    {   0,
        1,    1,    1,    1,    1,    1,    3,    4,    1,    7,
        8,   12,   12,  551,   12,   14,   14,   30,   14,    1,
       26,   26,  308,   26,    1,    1,   27,   27,  151,    1,
        1,    1,   27,    3,    4,   37,    7,    8,   32,   32,
       24,  311,   43,   43,   30,   43,   49,   49,    1,    1,
       24,    1,    2,    2,    2,    2,    2,    2,  153,   42,
        2,  226,   37,   47,   47,  151,   47,  308,   27,   42,
      161,    2,   27,   44,   44,  226,    2,    2,   96,   44,
      161,    2,    2,    2,   48,   48,  311,   48,   51,   51,
      234,   51,   49,   52,   52,  153,   52,   53,   53,  234,

        2,    2,  549,    2,    5,    5,    5,    5,    5,    5,
       63,   63,    5,   63,  417,   44,   64,   64,  106,   44,
       66,   66,   71,   71,   96,   66,   66,   81,   81,  417,
       81,   82,   82,    5,    5,    5,    6,    6,    6,    6,
        6,    6,  255,   53,    6,   65,   65,   83,   83,   84,
       84,   65,  255,   83,   84,   84,   89,   89,  439,   89,
       90,   90,   64,   90,  106,    6,    6,    6,    9,    9,
        9,    9,    9,    9,  244,  244,    9,   82,   91,   91,
       92,   92,  345,   92,   93,   93,  345,   65,  439,   83,
      548,   65,  345,   83,   94,   94,  524,    9,    9,    9,

       95,   95,   99,   99,  523,   99,  100,  100,  294,  100,
      101,  101,  102,  102,  518,  102,    9,    9,   10,   10,
       10,   10,   10,   10,   91,  294,   10,  103,  103,  183,
       93,  104,  104,  105,  105,  115,  115,  116,  116,  116,
       94,  123,  123,  124,  124,  124,   95,   10,   10,   10,
      128,  128,  117,  117,  125,  125,  101,  117,  117,  125,
      125,  130,  131,  131,  133,  163,   10,   10,  160,  185,
      160,  183,  441,  103,  163,  160,  163,  104,  421,  105,
      517,  115,  174,  174,  180,  180,  218,  123,  174,  516,
      180,  220,  130,  210,  210,  133,  128,  215,  215,  210,

      247,  247,  441,  215,  249,  249,  251,  251,  131,  140,
      140,  185,  421,  140,  140,  140,  514,  218,  512,  140,
      140,  140,  220,  140,  140,  235,  140,  140,  140,  235,
      276,  276,  277,  277,  278,  278,  334,  235,  336,  235,
      279,  279,  280,  280,  281,  281,  282,  282,  283,  283,
      295,  307,  307,  310,  310,  295,  353,  353,  354,  354,
      355,  355,  356,  356,  357,  357,  400,  295,  423,  334,
      402,  336,  358,  358,  374,  374,  495,  375,  375,  453,
      276,  455,  277,  376,  376,  479,  467,  377,  377,  469,
      279,  507,  280,  378,  378,  497,  282,  487,  283,  379,

      379,  307,  423,  310,  380,  380,  381,  381,  374,  400,
      481,  375,  501,  402,  489,  503,  509,  513,  479,  376,
      495,  374,  374,  377,  374,  375,  515,  487,  453,  378,
      455,  467,  507,  511,  469,  379,  519,  519,  510,  497,
      380,  508,  381,  481,  489,  520,  520,  521,  521,  522,
      522,  525,  525,  526,  526,  501,  506,  509,  503,  527,
      527,  528,  528,  529,  529,  530,  530,  531,  531,  513,
      532,  532,  533,  533,  534,  534,  535,  535,  515,  536,
      536,  537,  537,  538,  538,  540,  540,  540,  541,  541,
      541,  542,  542,  542,  543,  543,  543,  544,  544,  544,

      545,  545,  545,  546,  546,  546,  547,  547,  547,  550,
      550,  550,  552,  552,  552,  553,  553,  553,  554,  505,
      554,  555,  504,  555,  556,  556,  556,  557,  557,  557,
      502,  500,  499,  498,  496,  494,  492,  491,  490,  488,
      486,  485,  484,  483,  482,  480,  478,  476,  474,  473,
      471,  470,  468,  466,  465,  464,  463,  462,  461,  460,
      459,  458,  457,  456,  454,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  440,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  427,  426,  425,
      424,  422,  420,  419,  418,  416,  415,  414,  413,  412,

      411,  410,  409,  407,  406,  405,  404,  403,  401,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  352,  351,  349,  348,  347,  346,  344,  343,
      342,  341,  340,  339,  338,  337,  335,  333,  332,  330,
      329,  328,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  309,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  274,  273,

      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      261,  260,  259,  258,  257,  256,  254,  253,  252,  250,
      248,  245,  242,  241,  240,  239,  238,  237,  236,  233,
      232,  231,  230,  229,  228,  227,  225,  224,  223,  221,
      219,  217,  216,  214,  212,  211,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  189,  188,  187,  186,  184,
      182,  181,  179,  178,  177,  176,  175,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  162,  159,  158,
      157,  156,  155,  154,  152,  150,  149,  148,  146,  145,

      144,  143,  142,  139,  138,  137,  136,  135,  134,  132,
      129,  127,  126,  122,  121,  120,  119,  118,  114,  113,
      112,  111,  110,  109,  108,   97,   87,   86,   85,   80,
       79,   78,   73,   68,   67,   62,   61,   60,   59,   58,
       57,   56,   54,   50,   46,   41,   34,   25,   23,   22,
       21,   20,   18,   15,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../upcr/detect-upc/scanner.l"
#define INITIAL 0
#line 3 "../../upcr/detect-upc/scanner.l"
#include "detect-upc.h"
/* 
* UPC keywords and standard functions: the presence of any of these 
* in a file indicate that it contains UPC code for our purposes.
* Note that 'shared', 'strict' and 'relaxed' are handled separately
* to allow for their use as valid identifiers in C-mode headers.
*/
/* Since upc pragmas use a '^' start of line match, we can't
* group them together with the other rules */
#define INSTRING 1
#define INSHARED 2
#define OUTSTRING 3
#define OUTPUT 4
#define INUPCONLY 5
#define OUTUPCONLY 6

#line 763 "scanner.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 46 "../../upcr/detect-upc/scanner.l"

    if (do_output) 
        BEGIN OUTPUT;

#line 922 "scanner.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 540 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 855 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "../../upcr/detect-upc/scanner.l"
{ handle_include(yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "../../upcr/detect-upc/scanner.l"
{ BEGIN INUPCONLY; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "../../upcr/detect-upc/scanner.l"
{ mark_as_upc(yytext, PRAGMA);} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "../../upcr/detect-upc/scanner.l"
{ mark_as_c(yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "../../upcr/detect-upc/scanner.l"
{ mark_as_upc(yytext, LEXXER);} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "../../upcr/detect-upc/scanner.l"
{ mark_as_upc(yytext, LEXXER);} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "../../upcr/detect-upc/scanner.l"
{ BEGIN INSHARED; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "../../upcr/detect-upc/scanner.l"
{ BEGIN INSTRING; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK

 /*
  * following 'shared', 'relaxed' or 'strict':
  * Determine if the keyword is followed by an identifier-like word
  * (making it UPC) or not (making it C),
  * while ignoring []s which can appear legally in both C and UPC:
  * UPC:	shared [8] int *x;
  * C:		int relaxed[8][4];
  */

case 12:
YY_RULE_SETUP
#line 72 "../../upcr/detect-upc/scanner.l"
{ mark_as_upc("shared/relaxed/strict", LEXXER);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "../../upcr/detect-upc/scanner.l"
{ BEGIN INITIAL; }
	YY_BREAK

 /* 
  * input string literal: go until another double quote seen, but not
  * if it's preceded by a \ (unless it's a \\, i.e. a literal \)
  */

case 16:
YY_RULE_SETUP
#line 83 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 84 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 85 "../../upcr/detect-upc/scanner.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 86 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK

 /* On input, between the delimiters
  *   # line 1 "<START-UPC-ONLY>"
  * and
  *   # line 1 "<END-UPC-ONLY>"
  * we don't apply our UPC detection heuristics.
  * NOTE: These don't (yet) nest, but a "depth" counter could fix that.
  */

case 20:
YY_RULE_SETUP
#line 97 "../../upcr/detect-upc/scanner.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "../../upcr/detect-upc/scanner.l"
;
	YY_BREAK

 /* 
  * output string literal: go until another double quote seen, but not
  * if it's preceded by a \ (unless it's a \\, i.e. a literal \)
  */

case 22:
YY_RULE_SETUP
#line 106 "../../upcr/detect-upc/scanner.l"
{ print_out(yytext, yyleng); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 107 "../../upcr/detect-upc/scanner.l"
{ print_out(yytext, yyleng); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 108 "../../upcr/detect-upc/scanner.l"
{ print_out(yytext, yyleng);
                            BEGIN OUTPUT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 110 "../../upcr/detect-upc/scanner.l"
{ print_out(yytext, yyleng); }
	YY_BREAK

 /* On output, between the delimiters
  *   # line 1 "<START-UPC-ONLY>"
  * and
  *   # line 1 "<END-UPC-ONLY>"
  * we swallow the text if not in UPC mode, and always swallow the delimiters.
  * NOTE: These don't (yet) nest, but a "depth" counter could fix that.
  */

case 26:
YY_RULE_SETUP
#line 121 "../../upcr/detect-upc/scanner.l"
{ BEGIN OUTPUT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "../../upcr/detect-upc/scanner.l"
{ if (!in_c) print_out(yytext, yyleng); }
	YY_BREAK

 /* output scan: only care about when we enter file and
  * transforming of 'shared', 'strict' and 'relaxed'.
  */

case 28:
YY_RULE_SETUP
#line 129 "../../upcr/detect-upc/scanner.l"
{ insert_pragma(yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 130 "../../upcr/detect-upc/scanner.l"
{ BEGIN OUTUPCONLY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 131 "../../upcr/detect-upc/scanner.l"
{ print_out(yytext, yyleng);
                           BEGIN OUTSTRING; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "../../upcr/detect-upc/scanner.l"
{ if (in_c) print_out("_bupc_",6);
                           print_out(yytext, yyleng); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "../../upcr/detect-upc/scanner.l"
{ ; /* Swallow it, leaving a blank line for counting */ }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "../../upcr/detect-upc/scanner.l"
{ print_out(yytext, yyleng); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "../../upcr/detect-upc/scanner.l"
ECHO;
	YY_BREAK
#line 1224 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INSTRING):
case YY_STATE_EOF(INSHARED):
case YY_STATE_EOF(OUTSTRING):
case YY_STATE_EOF(OUTPUT):
case YY_STATE_EOF(INUPCONLY):
case YY_STATE_EOF(OUTUPCONLY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 540 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 540 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 539);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 138 "../../upcr/detect-upc/scanner.l"


/* 
 * we use only 1 file per run, so stop yylex() at EOF 
 */
int yywrap()
{
    return 1;
}

