SUBDIRS= . pt2pt
INCLUDES = -I${master_top_srcdir}/src/include -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES =			\
        mpid_abort.c				\
        mpid_buffer.c				\
        mpid_finalize.c				\
        mpid_getpname.c				\
        mpid_hooks.c				\
        mpid_init.c				\
        mpid_mem.c				\
        mpid_progress.c				\
        mpid_recvq.c				\
        mpid_request.c				\
        mpid_time.c				\
        mpid_vc.c
