SUBDIRS= . persistent
INCLUDES = -I${master_top_srcdir}/src/include -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES =			\
        mpid_cancel.c				\
        mpid_issend.c				\
        mpid_recv.c				\
        mpid_ssend.c				\
        mpidi_callback.c			\
        mpidi_callback_rzv.c			\
        mpidi_control.c				\
        mpidi_done.c				\
        mpidi_recvmsg.c				\
        mpidi_rendezvous.c			\
        mpidi_sendmsg.c
