SUBDIRS = mpi mpid util basic commands .
smvar_do_sharedlibs = 0
smvarSubdir_commonmake=
smvarSubdir_do_dependencies=no
smvar_dependenciesDummy=yes
distclean-local:
	rm -f runtests

testingio:
	(cd mpi && $(MAKE) testingio)

testing:
	(cd mpi && $(MAKE) testing)

testingvnm:
	(cd mpi && $(MAKE) testingvnm)

testing-mpirun:
	(cd mpi && $(MAKE) testing-mpirun)
testingvnm-mpirun:
	(cd mpi && $(MAKE) testingvnm-mpirun)
testingio-mpirun:
	(cd mpi && $(MAKE) testingio-mpirun)

testingdual-mpirun:
	(cd mpi && $(MAKE) testingdual-mpirun)

