# -*- mode: makefile-gmake; -*-
SUBDIRS= .
INCLUDES = -I${master_top_srcdir}/src/include -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES =			\
	mpid_comm.c mpid_selectcolls.c mpid_optcolls.c
